### ISSUE TITLE
Fails on  newer IntelliJ IDEA

### ISSUE THREAD

**Issue by fokot** [Jukkales/intellij-propertiessort#11]
Fails on `IntelliJ IDEA 2024.2.4`

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'de.juserv.SortPropertiesAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: de.juserv.intellij-propertiessort]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by Kaemmelot** [comment]
It seems this plugin is no longer developed, so I hope this advertisement is ok. I made my own plugin which should do the same as this one did: https://plugins.jetbrains.com/plugin/26642-data-file-sorter
https://github.com/Kaemmelot/IntelliJ-data-file-sorter
